### ISSUE TITLE
channel management--Edit channel

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.MC#10]
![image](https://user-images.githubusercontent.com/102500164/168535895-ed44196b-cee3-4027-9a94-0dae8e1b62f1.png)

![image](https://user-images.githubusercontent.com/102500164/168536363-093ca6df-2821-42f1-ba3b-aa4f86bfa442.png)
暗文显示，期望与第二张图片所标记的暗文显示位置一致

**Comment by wzh425** [comment]
已处理提交pr

**Comment by LazyEar0** [comment]
resolved
