### ISSUE TITLE
Global.Markdown editor input level 1 title, the font will overlap;

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#100]
Markdown编辑器中输入一级标题，字体会重叠；

![image](https://user-images.githubusercontent.com/95004531/174951214-18f2f97c-1eb9-4648-87a4-bbe2293f06a0.png)

**Comment by wzh425** [comment]
我没有看到这个问题

**Comment by LazyEar0** [comment]
resolved
