### ISSUE TITLE
Receiver group. New receiver group,Select the member drop-down box and manipulate the checkbox. The scrollbar position should not change

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#112]
新增消息组，选择组成员下拉框，勾选/取消勾选复选框，滚动条会自动回到顶部

预期结果：
滚动条的位置不变；

![image](https://user-images.githubusercontent.com/95004531/174978649-a07671d5-2113-40b8-95ff-f92b97da3679.png)

**Comment by wzh425** [comment]
这是一个糟糕的情况 我还没有解决它

**Comment by LazyEar0** [comment]
resolved
