### ISSUE TITLE
Receiver group. Edit receiver group,The check box for selected members should be checked

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#113]
编辑消息组，选择成员下拉框，已选择的成员是未选中的状态；

预期结果：
已选成员的勾选框应是选中状态；

![image](https://user-images.githubusercontent.com/95004531/174983844-a37cfe87-2544-435d-ae8c-ff9be279c7df.png)

![image](https://user-images.githubusercontent.com/95004531/174983737-6a917f2a-e744-4bdd-bf29-3d80f1500c5e.png)

**Comment by wzh425** [comment]
更新组件库后 貌似好像就好了？

**Comment by LazyEar0** [comment]
resolved
