### ISSUE TITLE
Receiver group. Add/edit receiver group - adding external Members，after the prompt text is displayed, the entered data is cleared

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#115]
消息组 - 新增消息组 - 添加外部成员，当数据填写错误，弹出提示后，已填写的内容被清空；

预期结果：
弹出提示后，已填写的内容不会被清空；

![image](https://user-images.githubusercontent.com/95004531/174987326-b380b39f-acf2-4d1e-9df3-5e9907e988c2.png)

**Comment by wzh425** [comment]
Merrorhandler will cause the contents in pmodal form to be emptied  @capdiem

**Comment by LazyEar0** [comment]
resolved
