### ISSUE TITLE
Receiver group. Add/edit receiver group - adding external Members，User nicknames can be in Chinese and English as well as numbers

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#116]
新增/编辑消息组 - 添加外部成员，用户昵称应支持  中文，英文和数字；

![image](https://user-images.githubusercontent.com/95004531/174987930-0dab1355-95e4-4ea6-ba94-cda7ae53ea4a.png)

![image](https://user-images.githubusercontent.com/95004531/174988001-15a81170-9605-41af-a1e8-9869a5f7046e.png)

**Comment by wzh425** [comment]
@wuweilai

**Comment by wzh425** [comment]
Demand auth adjustment

**Comment by LazyEar0** [comment]
与Auth的需求保持一致
