### ISSUE TITLE
Message management - Send message, send message popup, TAB style adjustment

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#120]
发送消息弹窗Tab样式调整：
1.按钮与Tab背景的上下间距调整
2.按钮宽度调整
3.鼠标移入后无悬浮样式

实际结果：
![image](https://user-images.githubusercontent.com/95004531/174994382-b8d1b88f-6191-45e4-ac42-a92361707081.png)

预期结果：
![image](https://user-images.githubusercontent.com/95004531/174994489-309b2efb-f70d-48d7-aae3-b24d5a8990a9.png)

**Comment by wzh425** [comment]
已更换步骤条组件

**Comment by LazyEar0** [comment]
resolved
