### ISSUE TITLE
Send message - recipient, batch upload, icon highlight click the mouse should be able to upload files

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#125]
发送消息 - 收件人，批量上传收件人，鼠标移入上传文件按钮时，icon高亮，鼠标所在区域应可点击上传，现在无法点击上传文件；

![image](https://user-images.githubusercontent.com/95004531/175190902-a5cc0f11-1b29-4a39-8d09-1ab33fe98b00.png)

**Comment by LazyEar0** [comment]
虚框内 鼠标移至除圆圈外的区域，icon会出现变亮的情况，当icon变亮时，点击没有弹出上传文件的框

**Comment by wzh425** [comment]
目前点击区域时一个正方形

**Comment by LazyEar0** [comment]
resolved
