### ISSUE TITLE
Create a channel

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.MC#13]
![image](https://user-images.githubusercontent.com/102500164/168542243-d5753e34-224e-45ff-8d20-c30e1919306f.png)
预期结果，长度超出应有提示，以及输入错误点击提交，应是点击提交失败

**Comment by wzh425** [comment]
1、需求里没有长度限制的要求；
2、调用邮箱前无法知道账号密码是否正确，我认为没有必要这样做

**Comment by LazyEar0** [comment]
无效问题
