### ISSUE TITLE
Send message - Recipient, manually selected, missing recipient statistics

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#132]
发送消息 - 收件人，手动选择收件人，缺少人数统计；
统计该条消息预计发送的人数；
![image](https://user-images.githubusercontent.com/95004531/175204427-0db9792d-8b7b-4f28-a409-be9c94de84a7.png)

**Comment by wzh425** [comment]
Not reflected in the design

**Comment by LazyEar0** [comment]
设计稿已更新

**Comment by LazyEar0** [comment]
resolved
