### ISSUE TITLE
Send message, switch to send rule, TAB location error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#135]
发送消息，消息内容tab点击下一步，切换至发送规则时，tab定位错误；
![image](https://user-images.githubusercontent.com/95004531/175221757-146983c4-592b-44d0-bfd8-4d9a2d881961.png)

**Comment by wzh425** [comment]
Waiting for component repair

**Comment by LazyEar0** [comment]
resolved
