### ISSUE TITLE
Send template messages - Message content style adjustments

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#138]
发送模板消息 - 消息内容样式调整
实际结果：
![image](https://user-images.githubusercontent.com/95004531/175227636-1ec3e289-f5d7-412b-81ab-cca6a45ab3d9.png)
![image](https://user-images.githubusercontent.com/95004531/175228100-6ecff359-618e-4b39-858c-d3d690c457d8.png)

预期结果：
![image](https://user-images.githubusercontent.com/95004531/175227825-d1ad9c9f-66dd-4dc5-ae7b-ca77a7b759f5.png)
![image](https://user-images.githubusercontent.com/95004531/175228003-268b965e-42b9-44c5-9910-773765a6ef00.png)

**Comment by wzh425** [comment]
消息内容是个富文本   多行文本框并不适用
