### ISSUE TITLE
Send message - Send rule. When the check box is not selected, the input box should be gray and cannot be entered

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#143]
发送消息 - 发送规则，当勾选框未选中时，输入框应是置灰不可输入的状态；

![image](https://user-images.githubusercontent.com/95004531/175236391-4b1e57a3-4953-4aec-874e-9c94074c57ce.png)

**Comment by wzh425** [comment]
需求已变更

**Comment by LazyEar0** [comment]
resolved
