### ISSUE TITLE
Global. Icon adjustment for list field sorting

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#146]
全局，列表字段排序的icon调整。

实际结果：
![image](https://user-images.githubusercontent.com/95004531/175238240-acd2b56e-5e75-4a05-acbb-16757fb1057c.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/175238350-da5177a0-161a-47ca-b343-28f188c9464e.png)

**Comment by wzh425** [comment]
等待组件支持
