### ISSUE TITLE
Message task list - View tasks. The task history is more than one page and is not fully displayed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#160]
消息任务列表 - 查看任务，任务历史超过一页，显示不全；

![image](https://user-images.githubusercontent.com/95004531/175265163-c740ddfc-a83c-4ae3-8747-1025eb1c8641.png)

**Comment by wzh425** [comment]
What is your screen resolution

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by wzh425** [comment]
加滚动条

**Comment by LazyEar0** [comment]
resolved
