### ISSUE TITLE
Message task list - delete, delete message task in enable state, prompt copywriting should be translated into Chinese;

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#172]
消息任务列表 - 删除，启用状态下删除消息任务，提示文案应翻译为中文；

![image](https://user-images.githubusercontent.com/95004531/175467968-5e4339f2-5aae-40da-b3e7-6c67ae0d57ec.png)

**Comment by wzh425** [comment]
待框架支持
