### ISSUE TITLE
Message task list, message task status of the list Does not obtain the task status of the task history

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#174]
消息任务列表，列表的消息任务状态没有自动获取任务历史的任务状态
![image](https://user-images.githubusercontent.com/95004531/175469518-bd76aca9-27f9-4a89-8b8e-88ea0f3aa30a.png)
![image](https://user-images.githubusercontent.com/95004531/175469569-391327ac-edfc-40bb-859f-004ee196c4ea.png)

**Comment by LazyEar0** [comment]
![image](https://user-images.githubusercontent.com/95004531/176601827-5097e066-2c17-4e90-929e-c608cf7cb027.png)
![image](https://user-images.githubusercontent.com/95004531/176601853-7b47512e-0201-4b1c-b61c-7e55f7947ed8.png)

消息任务的状态应显示在消息任务列表，目前只显示了发送成功的状态

**Comment by wzh425** [comment]
这是老数据 新发送的消息试试

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: LazyEar0 ***@***.***>
发送时间: Thursday, June 30, 2022 1:47:43 PM
收件人: masastack/MASA.MC ***@***.***>
抄送: wzh425 ***@***.***>; Assign ***@***.***>
主题: Re: [masastack/MASA.MC] Message task list, message task status of the list Does not obtain the task status of the task history (Issue #174)


[image]<https://user-images.githubusercontent.com/95004531/176601827-5097e066-2c17-4e90-929e-c608cf7cb027.png>
[image]<https://user-images.githubusercontent.com/95004531/176601853-7b47512e-0201-4b1c-b61c-7e55f7947ed8.png>

消息任务的状态应显示在消息任务列表，目前只显示了发送成功的状态

―

**Comment by LazyEar0** [comment]
resolved
