### ISSUE TITLE
Message Task list - View tasks, task history list does not generate the corresponding task history

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#175]
操作步骤：
1.发送消息，渠道类型为站内信时，发送广播的消息任务，设置发送规则为每1秒发送1条消息；
2.查看消息任务历史列表；

实际结果：
仅有一条消息任务历史；
预期结果：
应根据发送规则生成对应的任务历史；

![image](https://user-images.githubusercontent.com/95004531/175470011-52c71807-f5c6-435e-b0fa-f7e5be2cb72b.png)

**Comment by wzh425** [comment]
Waiting for docking scheduler

**Comment by LazyEar0** [comment]
resolved
