### ISSUE TITLE
Message record list, list style needs to be adjusted;

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#177]
消息记录列表，列表样式需调整；
1.每列的宽度固定；
2.时间列 表头和数据未对齐；
3.搜索和分页固定，滚动条显示在列表区域；
实际结果：
![image](https://user-images.githubusercontent.com/95004531/175471144-116228ab-a4a0-4aee-b6bf-c41a7fc8ebb4.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/175471250-5384e600-fa2e-43b9-aa64-9fb1fdb7ab25.png)

**Comment by wzh425** [comment]
设计里每列宽度并没有一样

**Comment by LazyEar0** [comment]
resolved
