### ISSUE TITLE
Message record list, Advanced search, and list are missing "message task batches"

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#182]
消息记录列表，高级搜索和列表缺少“消息任务批次”；
实际结果：
![image](https://user-images.githubusercontent.com/95004531/175474154-fdfd06b2-6160-43be-9d6f-384ec06cce6a.png)

预期结果：
![image](https://user-images.githubusercontent.com/95004531/175473343-7fdbc831-7837-43c5-b4fb-4b56b7cf7e5a.png)

**Comment by wzh425** [comment]
显示不下

**Comment by LazyEar0** [comment]
resolved
