### ISSUE TITLE
Message record list,  withdrawn messages, send status should be failed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#184]
消息记录列表，撤回的消息，发送状态应该是“发送失败”，失败原因是：撤回消息；
![image](https://user-images.githubusercontent.com/95004531/175474636-feec6194-9526-4666-8197-0ec432a16bb4.png)

**Comment by wzh425** [comment]
显示不下

**Comment by LazyEar0** [comment]
resolved
