### ISSUE TITLE
Send message. The message is periodically sent. The historical status of the message task is incorrect

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#185]
发送消息，定时发送的消息，消息任务历史的状态应是“待发送”；

目前是发送成功；

![image](https://user-images.githubusercontent.com/95004531/175475186-1904918a-85d0-4f8a-870c-0981bbbbd7dc.png)

**Comment by wzh425** [comment]
Currently, there is no scheduled task connected to the scheduler. Do you want to execute it now

**Comment by LazyEar0** [comment]
没有连接调度器的情况下，定时发送的任务不会被执行

**Comment by LazyEar0** [comment]
resolved
