### ISSUE TITLE
 note

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.MC#19]
![image](https://user-images.githubusercontent.com/102500164/168719275-dd8fad4f-a567-4c5c-8216-6f525273f23b.png)
![image](https://user-images.githubusercontent.com/102500164/168719329-b1a365a5-0e07-4973-804e-5188026f9df9.png)
点击关闭高级搜索应跟第二张图片一致

**Comment by wzh425** [comment]
已处理提交pr

**Comment by LazyEar0** [comment]
高级筛选的图标反了；
此问题暂时先关闭，待界面根据ui设计稿1：1还原，测试ui时，再验证此问题。
