### ISSUE TITLE
Message record list. Message records of some message tasks are missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#190]
操作步骤：
1.发送普通消息 - 收件人：广播 - 渠道类型：站内信 - 有跳转链接 - 保存并发送；
2.进入消息记录列表查看消息记录；

实际结果：
不显示该条消息任务的消息记录

![image](https://user-images.githubusercontent.com/95004531/175477778-49e561d1-24bc-4653-af0f-8ec2af704769.png)
![image](https://user-images.githubusercontent.com/95004531/175477861-32088191-14cf-4b0b-9d4d-601a78807b25.png)

**Comment by wzh425** [comment]
I haven't reproduced this problem yet

**Comment by LazyEar0** [comment]
resolved
