### ISSUE TITLE
Message record list - Mobile phone number or email search recipient, search results cannot be displayed in a timely manner

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#192]
消息记录列表，使用手机号或邮箱 搜索收件人，输入内容后不显示搜索结果，清除搜索内容后才显示搜索结果

![image](https://user-images.githubusercontent.com/95004531/175479079-6bf3a19b-5810-4547-867a-942a428c75ad.png)
![image](https://user-images.githubusercontent.com/95004531/175479204-36b60998-ed09-4bd9-ad5c-9ba675ccd364.png)

**Comment by wzh425** [comment]
@15168440402

**Comment by LazyEar0** [comment]
resolved
