### ISSUE TITLE
Drafts in the enabled state will automatically change to the disabled state after being edited and saved

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#302]
消息任务：启用状态的草稿，编辑保存后，会自动变为禁用状态
![image](https://user-images.githubusercontent.com/95004531/211750610-3c0e5c1d-278c-415f-b130-9bfb9d52ea06.png)

**Comment by LazyEar0** [comment]
草稿是否需要“启用”/“禁用”？草稿的启用禁用有什么意义

**Comment by xyfy** [comment]
@LazyEar0  目前的逻辑，如果是草稿是不能启用的，应该是考虑它可能设置不齐全，应该禁用

这个要不要考虑去除列表上可以设置草稿为启用状态的逻辑？

**Comment by xie1wei2** [comment]
安全性的逻辑是在使用中的任何程序如果进行编辑修改后，状态都会切换至禁用状态。编辑完毕以后需要再点击开启。如果是草稿那么一定不是启用状态。编辑草稿依然是禁用状态。

**Comment by LazyEar0** [comment]
草稿都是禁用的状态
