### ISSUE TITLE
Switch left menu, message template error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#336]
频繁切换左侧菜单，消息模板时，会报错
![image](https://user-images.githubusercontent.com/95004531/224229861-2b71101e-9b97-4bb3-88fe-cbac8408ad9f.png)

![image](https://user-images.githubusercontent.com/95004531/224229386-d1d60e7c-c7d7-4e68-9add-33d251fa3195.png)
![image](https://user-images.githubusercontent.com/95004531/224229524-b0e3ab68-3979-4f97-87d0-c107584b640c.png)

**Comment by LazyEar0** [comment]
此问题还是会出现

**Comment by wzh425** [comment]
Masa.Blazor 的EllipsisText组件有资源释放问题， 已提交pr 等待blazor发版
