### ISSUE TITLE
The mouse style changes when the mouse moves over the View button

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#341]
鼠标移至上传文件/View按钮上，鼠标样式发生变化，鼠标应仍是点击的样式
![image](https://user-images.githubusercontent.com/95004531/224925629-bc324892-7135-4a1b-a407-3ed222c3cef1.png)

![image](https://user-images.githubusercontent.com/95004531/224924199-afbad6b0-5069-4f90-a83f-c9b12b5a3190.png)

**Comment by LazyEar0** [comment]
鼠标移至查看时，仍存在此问题
![image](https://user-images.githubusercontent.com/95004531/225582100-1afb1004-98cf-4cf4-a869-1264c7062b1a.png)

**Comment by binwan-dev** [comment]
It is wait for merge [pr](https://github.com/masastack/MASA.MC/pull/362)
