### ISSUE TITLE
View the recipient popup, now according to the number of page data adaptive height

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#342]
查看收件人弹窗，现根据页面数据条数自适应高度，应固定高度，不能根据页面条数自适应高度
![image](https://user-images.githubusercontent.com/95004531/224926415-9150e87a-f598-4557-9f19-c67b3ea64351.png)

**Comment by MayueCif** [comment]
高度值找谢伟确认

**Comment by xie1wei2** [comment]
![image](https://user-images.githubusercontent.com/101324746/225258684-20116278-9dc8-41f4-a74e-b73a8dac38ac.png)
