### ISSUE TITLE
After the recipient is successfully uploaded, click the Upload file button again to replace the uploaded file. The page crashes

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#343]
上传收件人成功后，再次点击上传文件按钮，更换上传的文件，页面崩溃
![image](https://user-images.githubusercontent.com/95004531/224925731-49aa94f3-edc6-4fad-af36-0b731e6dfc5c.png)

**Comment by LazyEar0** [comment]
取消选择本地文件时，去掉请选择文件提示框
![image](https://user-images.githubusercontent.com/95004531/225580687-ff07b1f8-03c5-488e-b4e6-67640ca17053.png)

**Comment by binwan-dev** [comment]
[fixed](https://github.com/masastack/MASA.MC/pull/365/files) this pr
