### ISSUE TITLE
Test message task, select recipient, user nickname missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#348]
测试消息任务，选择收件人时，用户昵称缺失
![image](https://user-images.githubusercontent.com/95004531/224939973-df46f43b-7ef7-43d5-8a75-b6017e70cd2b.png)

**Comment by kogel-net** [comment]
#361

**Comment by LazyEar0** [comment]
昵称放到上面
![image](https://user-images.githubusercontent.com/95004531/225569547-f7127d36-b7eb-476f-a92e-27c7935a8aba.png)
