### ISSUE TITLE
The message record searches for the recipient, and after selecting the user, the user nickname should be displayed in the search box

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#351]
消息记录搜索收件人，选择用户后，搜索框中应显示用户昵称，Autocomplete结果也没有用户昵称
![image](https://user-images.githubusercontent.com/95004531/224946976-258fba7f-a0f5-4bd2-a5f1-fcecdeda4e40.png)

**Comment by kogel-net** [comment]
#366
