### ISSUE TITLE
Message record, advanced search, drop down TAB truncated

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#384]
消息记录，高级搜索，下拉框标签被截断。请自查其他页面
![image](https://user-images.githubusercontent.com/95004531/227486227-75c9989f-a4c2-403e-b291-d8f66664c15d.png)

**Comment by zyz** [comment]
#405 Message record, advanced search, Select component text is truncated.

**Comment by LazyEar0** [comment]
@zyz 此问题仍存在

**Comment by zyz** [comment]
![图片](https://user-images.githubusercontent.com/714535/229697455-1ad3a605-b3df-4dee-99be-e836d24da404.png)

**Comment by zyz** [comment]
https://github.com/masastack/MASA.Stack.Components/pull/458
