### ISSUE TITLE
After successfully adding an external member, when you add it again, opening a popover immediately triggers form validation

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#390]
添加外部成员成功后，再次添加时，打开弹窗立即触发了表单验证
![image](https://user-images.githubusercontent.com/95004531/227825977-1ce73465-5374-4b89-9705-a044f3af3397.png)

**Comment by zyz** [comment]
#405 Fix: After successfully adding an external member, when you add it again, opening a popover immediately triggers form validation.

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by zyz** [comment]
#410
