### ISSUE TITLE
Look up prompt i18n

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#391]
自查提示语i18n
![image](https://user-images.githubusercontent.com/95004531/227826174-981839f3-f497-4616-8b74-c1c4b86661e1.png)

**Comment by zyz** [comment]
#405 Look up prompt i18n (Modal dialog)

**Comment by LazyEar0** [comment]
![image](https://user-images.githubusercontent.com/95004531/229671431-a7d8bc0c-0d3d-4f50-bc1d-a7559fb8e3bf.png)

**Comment by zyz** [comment]
#410
