### ISSUE TITLE
When the drop-down box is selected, the ability to clear the selected box is missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#411]
下拉框选中后，缺少清除已选项功能，请自查其他页面的下拉框。
实际结果
![image](https://user-images.githubusercontent.com/95004531/229692434-a1548c65-1edd-48f8-814c-994b27628c17.png)
预期结果
![image](https://user-images.githubusercontent.com/95004531/229692555-1757535e-12b4-4e61-acde-54861ad04be5.png)

**Comment by zyz** [comment]
#415
