### ISSUE TITLE
Page error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#417]
页面报错
![企业微信截图_16808482763783](https://user-images.githubusercontent.com/95004531/230563330-3fd3d781-948b-4fe2-b65e-6327f318b4d0.png)

![image](https://user-images.githubusercontent.com/95004531/230563314-e3fed90d-cbc3-450f-a7fb-83e985044854.png)

**Comment by kogel-net** [comment]
https://github.com/masastack/BlazorComponent/pull/376

**Comment by kogel-net** [comment]
等待Masa.Blazor包升级
