### ISSUE TITLE
Switch menu to enter message log error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#436]
切换菜单进入消息记录报错
![企业微信截图_16817141021866](https://user-images.githubusercontent.com/95004531/232408935-7504bddc-df7b-42c5-91ac-e779993ee7f6.png)

**Comment by wzh425** [comment]
没有复现  rancher上日志也搜不到了 等下次复现第一时间查看日志

**Comment by LazyEar0** [comment]
![image](https://user-images.githubusercontent.com/95004531/233006544-2d2a0805-6e1d-489e-940f-6e026fe2ff3f.png)

**Comment by wzh425** [comment]
能否提供下复现的流程

**Comment by wzh425** [comment]
https://github.com/masastack/BlazorComponent/pull/390
