### ISSUE TITLE
The recipient cannot search for the user

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#450]
收件人搜索不到用户
![image](https://user-images.githubusercontent.com/95004531/233013260-a7e778a9-3d6e-4c23-9531-371ed19ec4c1.png)

**Comment by wzh425** [comment]
@wuweilaiya  @MayueCif

**Comment by LazyEar0** [comment]
目前仅支持名称搜索，且名称搜索有时搜不到用户。应支持用名称，手机号，邮箱均可搜索
![image](https://user-images.githubusercontent.com/95004531/233551968-73b289f3-79a8-49c3-8cd2-e0942045ffb8.png)
![image](https://user-images.githubusercontent.com/95004531/233552163-2664d6df-792a-4c78-8a57-88ce07fb343d.png)
![image](https://user-images.githubusercontent.com/95004531/233552243-f45380fe-6e21-4767-8f72-969c352acef3.png)
