### ISSUE TITLE
Upload the specified recipient error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#463]
上传的文件数据错误时，上传指定收件人报错
![image](https://user-images.githubusercontent.com/95004531/234191790-4a1257be-56de-4978-92f9-5aefb3484ecb.png)

![image](https://user-images.githubusercontent.com/95004531/234191725-cfd43705-c0b8-45b0-9824-d7ffc505d5fc.png)
文件：
[ReceiverImportTemplate (15).csv](https://github.com/masastack/MASA.MC/files/11319345/ReceiverImportTemplate.15.csv)

**Comment by xyfy** [comment]
#465
