### ISSUE TITLE
Send a message to a role or a message group containing a role. After successful delivery, the actual recipient is wrong

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#474]
发送消息，收件人为角色/包含角色的消息组，发送成功后，实际收件人仅有“员工”身份的用户，应包含“用户身份”的用户
![image](https://user-images.githubusercontent.com/95004531/234831998-8772f0ec-38ed-443c-b930-16670e25e8e2.png)

**Comment by wzh425** [comment]
@MayueCif
