### ISSUE TITLE
Global. Advanced search drop-down options, style adjustment;

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#72]
高级搜索的下拉选项，样式调整；
实际结果：
![image](https://user-images.githubusercontent.com/95004531/174739367-eaca6118-e9a2-4ed0-b7a7-3923f524fbb0.png)
预期结果：
文本和按钮中间有一条小竖线
下拉按钮的大小也不一样

![image](https://user-images.githubusercontent.com/95004531/174739647-fff20cd4-7128-4176-98cf-67964b2d9d99.png)

**Comment by wzh425** [comment]
@capdiem

**Comment by MapleWithoutWords** [comment]
already resolve .need wait ```MASA.Stack.Component``` published
![WXWorkCapture_1677307053577](https://user-images.githubusercontent.com/38368335/221343347-043df069-e316-47b2-b634-c31ae25ac179.png)

**Comment by MapleWithoutWords** [comment]
https://github.com/masastack/MASA.Stack.Components/pull/349
