### ISSUE TITLE
Global. The menu should not be expanded when the "Clear" button is clicked in the drop-down box

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#75]
下拉框点击“清空”按钮；
实际结果：
清空内容并展开下拉菜单；
预期结果：
清空内容不展开下拉菜单；

![image](https://user-images.githubusercontent.com/95004531/174741756-83b3b8c5-2b98-4328-8ca4-6d5bab51a690.png)

**Comment by wzh425** [comment]
@capdiem

**Comment by LazyEar0** [comment]
resolved
