### ISSUE TITLE
Global. Channel drop down menu style optimization when channel name is too long

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#76]
当渠道名称过长时，渠道下拉框的样式需要优化；
![image](https://user-images.githubusercontent.com/95004531/174742292-71ec31f2-8546-4852-a6a5-ba11e1a737a2.png)

**Comment by wzh425** [comment]
需要如何优化呢 @LazyEar0

**Comment by MapleWithoutWords** [comment]
> 需要如何优化呢 @LazyEar0

If the name is longer than a few sizes, it is hidden, and when the mouse moves up, a 'tips' is displayed to show everything.
what do you think?

**Comment by MapleWithoutWords** [comment]
the bug need wait MASA.Blazor publish. MASA.Blazor already solve.
