### ISSUE TITLE
Message templates - SMS, Add/edit templates, select templates drop - down menu message templates should be associated with channels

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#86]
操作步骤：

1. 消息模板 - 短信，新增消息模板；
2. 渠道选择“A渠道”，查看选择模板下拉框，显示“A渠道”的第三方模板；
3. 将渠道切换至“B渠道”，查看选择模板下拉框，仍显示“A渠道”的第三方模板；
![image](https://user-images.githubusercontent.com/95004531/174766331-a3a2045f-9eb1-4879-9809-fc4f4a6167eb.png)
4.选中某一模板，选择渠道的数据为空，下方出现选中模板的数据；
![image](https://user-images.githubusercontent.com/95004531/174768847-227b9958-8adb-4fbf-a290-5a9e58506bcc.png)

预期结果：
切换渠道后，选择模板下拉菜单中的第三方模板随着渠道发生变化，显示所选渠道的第三方模板数据；

**Comment by wzh425** [comment]
This is masa The bug of blazor 0.5 will be fixed in the next release

**Comment by LazyEar0** [comment]
resolved
