### ISSUE TITLE
Message templates - SHORT messages, new/edit templates, variables missing validation rules

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.MC#88]
消息模板 - 短信，新增/编辑消息模板，变量字典的变量内容格式及长度未限制；

预期结果：
1. 必填
2. 内容格式：支持英文，数字，符号；
3. 内容长度：2~50位；

![image](https://user-images.githubusercontent.com/95004531/174771247-c9e3a828-88ff-48a7-940f-1a42093b43c6.png)

**Comment by wzh425** [comment]
已沟通不需要限制了

**Comment by LazyEar0** [comment]
resolved
